import { writable } from 'svelte/store';
import { browser } from '$app/environment';

export type Language = 'en' | 'zh';

// Create a language store
const createLanguageStore = () => {
    const storedValue = browser ? localStorage.getItem('language') : null;
    const initial: Language = (storedValue as Language) || 'en';
    
    const { subscribe, set, update } = writable<Language>(initial);
    
    return {
        subscribe,
        set: (value: Language) => {
            if (browser) {
                localStorage.setItem('language', value);
            }
            set(value);
        },
        toggle: () => update(current => {
            const newValue: Language = current === 'en' ? 'zh' : 'en';
            if (browser) {
                localStorage.setItem('language', newValue);
            }
            return newValue;
        })
    };
};

export const language = createLanguageStore();

// Translation strings
export const translations = {
    en: {
        // Navigation
        'nav.performance': 'Performance',
        'nav.remap': 'Remap',
        'nav.lighting': 'Lighting',
        'nav.advancedkey': 'Advanced Keys',
        'nav.calibration': 'Calibration',
        'nav.debug': 'Debug',
        'nav.settings': 'Settings',
        'nav.about': 'About',
          // UI Elements
        'ui.sync': 'Sync',
        'ui.profiles': 'Profiles',
        'ui.import': 'Import',
        'ui.export': 'Export',
        'ui.back': 'Back',
        'ui.themeColors': 'Theme Colors',
        'ui.lightMode': 'Light Mode',
        'ui.darkMode': 'Dark Mode',
        'ui.language': 'Language',
        'ui.layer': 'Layer',
          // Common
        'common.zellia': 'Zellia Control',
        'common.english': 'English',
        'common.chinese': '中文',
        
        // Performance Page
        'performance.title': 'Performance',
        'performance.selectAllKeys': 'Select all keys',
        'performance.discardSelection': 'Discard selection',
        'performance.actuationPoint': 'Actuation Point',
        'performance.actuationPointDesc': 'Set the actuation point for your keys.',
        'performance.actuationPointLabel': 'ACTUATION POINT',
        'performance.sensitivityWarning': 'the key may be too sensitive, causing instability, please be careful',        'performance.rapidTrigger': 'Rapid Trigger',
        'performance.rapidTriggerDesc': 'Rapid Trigger dynamically actuates and resets your key based on your movement.',
        'performance.continuousRapidTrigger': 'Continuous Rapid Trigger',
        'performance.continuousRapidTriggerDesc': 'Maintain rapid trigger state continuously.',        'performance.sensitivity': 'Sensitivity',
        'performance.separateSensitivity': 'Separate Press/Release Sensitivity',
        'performance.pressSensitivity': 'Press Sensitivity','performance.releaseSensitivity': 'Release Sensitivity',
        'performance.enableRapidTrigger': 'Enable Rapid Trigger',
        'performance.enableContinuousRapidTrigger': 'Enable Continuous Rapid Trigger',
        'performance.continuousRapidTriggerFullDesc': 'When enabled, Rapid Trigger ends when the entire key is released. When disabled, Rapid Trigger ends at the actuation point.',
        'performance.rapidTriggerSensitivity': 'Rapid Trigger Sensitivity',        'performance.adjustSensitivity': 'Adjust the sensitivity for rapid trigger.',
        'performance.pressSensitivityLabel': 'PRESS SENSITIVITY',
        'performance.releaseSensitivityLabel': 'RELEASE SENSITIVITY',
        'performance.sensitivityLabel': 'SENSITIVITY',
        'performance.keysSelected': 'keys selected',
        'performance.high': 'HIGH',
        'performance.low': 'LOW',
        'performance.directInput': 'Direct input',
        
        // Lighting Page
        'lighting.color': 'Color',
        'lighting.static': 'Static',
        'lighting.staticDesc': 'Single solid color',
        'lighting.breathing': 'Breathing',
        'lighting.breathingDesc': 'Smooth fade in and out',
        'lighting.wave': 'Wave',
        'lighting.waveDesc': 'Color wave across keyboard',
        'lighting.ripple': 'Ripple',
        'lighting.rippleDesc': 'Ripple effect on keypress',
        'lighting.rainbow': 'Rainbow',
        'lighting.rainbowDesc': 'Cycling rainbow colors',
        'lighting.reactive': 'Reactive',
        'lighting.reactiveDesc': 'Color change on keypress',
        'lighting.spectrum': 'Spectrum',
        'lighting.spectrumDesc': 'Color spectrum cycling',
        'lighting.gradient': 'Gradient',
        'lighting.gradientDesc': 'Custom color gradient',
        'lighting.direction': 'Direction',
        'lighting.leftToRight': 'Left to Right',
        'lighting.rightToLeft': 'Right to Left',
        'lighting.topToBottom': 'Top to Bottom',
        'lighting.bottomToTop': 'Bottom to Top',
        'lighting.centerOut': 'Center Out',
        'lighting.outsideIn': 'Outside In',
        
        // Lighting UI
        'lighting.applySettings': 'Apply Settings',
        'lighting.perKeyMode': 'Per-Key Mode',
        'lighting.exitPerKeyMode': 'Exit Per-Key Mode',
        'lighting.colorSettings': 'Color Settings',
        'lighting.perKeyModeActive': 'Per-Key Mode Active',
        'lighting.clickKeysToSelect': 'Click keys on the keyboard to select them',
        'lighting.keyColor': 'Key Color',
        'lighting.selectKey': 'Select Key',
        'lighting.deselectKey': 'Deselect Key',
        'lighting.clear': 'Clear',
        'lighting.applyToSelectedKeys': 'Apply to Selected Keys',
        'lighting.gradientColors': 'Gradient Colors',
        'lighting.addColor': 'Add Color',
        'lighting.preview': 'Preview',
        'lighting.automaticColors': 'This effect uses automatic colors',
        'lighting.noColorSettings': 'No color settings needed for this effect',        'lighting.animatedEffect': 'Animated Effect',
        'lighting.reactiveEffect': 'Reactive Effect',
        'lighting.rgbValues': 'RGB: {0}, {1}, {2}',        // Advanced Key Pages
        'advancedkey.title': 'Advanced Keys',
        'advancedkey.subtitle': 'Configure advanced keyboard behaviors for enhanced productivity',
        'advancedkey.gettingStarted': 'Getting Started',
        'advancedkey.step1Title': 'Select a Mode',
        'advancedkey.step1Desc': 'Choose the advanced key behavior you want to configure',
        'advancedkey.step2Title': 'Select Keys',
        'advancedkey.step2Desc': 'Click on keys in the keyboard layout to configure them',
        'advancedkey.step3Title': 'Apply Settings',
        'advancedkey.step3Desc': 'Save your configuration to the keyboard',
        'advancedkey.infoDesc': 'Advanced key configurations allow you to customize how individual keys behave beyond standard typing. Each mode offers unique functionality to enhance your keyboard experience.',
        
        // Advanced Key Modes
        'advancedkey.tapHold': 'Tap Hold',
        'advancedkey.tapHoldDesc': 'Different actions for tap vs hold',
        'advancedkey.tapHoldFeature1': 'Quick tap action',
        'advancedkey.tapHoldFeature2': 'Hold action with configurable delay',        'advancedkey.tapHoldFeature3': 'Perfect for modifier keys',
        'advancedkey.tapHoldFeature4': 'Customizable timing',        'advancedkey.tapHoldTip': 'Tap-hold keys are perfect for modifier keys that can also function as regular keys when tapped quickly',        'advancedkey.quickTap': 'Quick tap (under {0}ms)',
        'advancedkey.holdOver': 'Hold (over {0}ms)',
        
        'advancedkey.toggle': 'Toggle',
        'advancedkey.toggleDesc': 'Toggle between two states',
        'advancedkey.toggleFeature1': 'Toggle on press or release',
        'advancedkey.toggleFeature2': 'Perfect for Caps Lock behavior',
        'advancedkey.toggleFeature3': 'State persistence',        'advancedkey.toggleFeature4': 'Visual feedback',
        'advancedkey.toggleDescription': 'This key will toggle {0} {1}. Each trigger will switch between active and inactive states.',
        'advancedkey.whenPressed': 'when pressed',
        'advancedkey.whenReleased': 'when released',
        
        'advancedkey.dynamic': 'Dynamic Key Stroke',
        'advancedkey.dynamicDesc': 'Interactive keystroke configuration',
        'advancedkey.dynamicFeature1': '4-phase keystroke control',
        'advancedkey.dynamicFeature2': 'Analog input response',
        'advancedkey.dynamicFeature3': 'Multiple key bindings',
        'advancedkey.dynamicFeature4': 'Advanced customization',
        
        'advancedkey.nullBind': 'Null Bind',
        'advancedkey.nullBindDesc': 'Rapid trigger with SOCD cleaning',
        'advancedkey.nullBindFeature1': 'Rapid trigger technology',
        'advancedkey.nullBindFeature2': 'SOCD (Simultaneous Opposing Cardinal Directions)',
        'advancedkey.nullBindFeature3': 'Perfect for gaming',
        'advancedkey.nullBindFeature4': 'Ultra-responsive input',
        
        // Tap-Hold Page
        'advancedkey.tapHoldTitle': 'Tap-Hold Configuration',
        'advancedkey.tapHoldSubtitle': 'Configure different actions for quick taps versus long holds',
        'advancedkey.tapAction': 'Tap Action',
        'advancedkey.holdAction': 'Hold Action',
        'advancedkey.holdDelay': 'Hold Delay',
        'advancedkey.tapTimeout': 'Tap Timeout',
        'advancedkey.milliseconds': 'milliseconds',
        'advancedkey.tapActionDesc': 'Action performed on quick tap',
        'advancedkey.holdActionDesc': 'Action performed when held',
        'advancedkey.holdDelayDesc': 'Time before hold action activates',
        'advancedkey.tapTimeoutDesc': 'Maximum time for tap detection',
        'advancedkey.configuredTapHold': 'Configured Tap-Hold Keys',
        'advancedkey.actionCategories': 'Action Categories',
        'advancedkey.common': 'Common',
        'advancedkey.modifiers': 'Modifiers',
        'advancedkey.function': 'Function',
        'advancedkey.letters': 'Letters',
        'advancedkey.backToAdvanced': 'Back',
        'advancedkey.applyConfiguration': 'Apply Configuration',
        'advancedkey.resetConfiguration': 'Reset Configuration',
        
        // Null Bind Page
        'advancedkey.nullBindTitle': 'Null Bind Configuration',
        'advancedkey.nullBindSubtitle': 'Configure rapid trigger with SOCD cleaning for gaming',
        'advancedkey.socdBehavior': 'SOCD Behavior',
        'advancedkey.lastInput': 'Last Input',
        'advancedkey.lastInputDesc': 'The most recently pressed key takes priority',
        'advancedkey.absolutePriority1': 'Absolute Priority Key1',
        'advancedkey.absolutePriority1Desc': 'First selected key always has priority',
        'advancedkey.absolutePriority2': 'Absolute Priority Key2',
        'advancedkey.absolutePriority2Desc': 'Second selected key always has priority',
        'advancedkey.neutral': 'Neutral',
        'advancedkey.neutralDesc': 'Both keys are released when conflicting',        'advancedkey.distance': 'Distance',
        'advancedkey.distanceDesc': 'Key with greater travel distance wins',
        
        // Null Bind Page - Additional translations
        'advancedkey.selectTwoKeys': 'Select Two Keys',
        'advancedkey.selectTwoKeysDesc': 'Click on two opposing keys in the keyboard layout to configure null bind behavior. Keys will be added automatically.',
        'advancedkey.firstKey': 'First Key',
        'advancedkey.secondKey': 'Second Key',
        'advancedkey.clickKeyToSelect': 'Click a key to select',
        'advancedkey.clickOpposingKey': 'Click opposing key',
        'advancedkey.remove': 'Remove',
        'advancedkey.resetSelection': 'Reset Selection',
        'advancedkey.selectedKeys': 'Selected Keys',
        'advancedkey.configureNullBindBehavior': 'Configure Null Bind Behavior',
        'advancedkey.selectHowToResolveKeyEvents': 'Select how to resolve the key events when both keys are pressed.',
        'advancedkey.lastInputBehavior': 'Last Input',
        'advancedkey.lastInputBehaviorDesc': 'The most recently pressed key takes priority over the previously held key',
        'advancedkey.absolutePriority1Behavior': 'Absolute Priority Key1',
        'advancedkey.absolutePriority1BehaviorDesc': 'First selected key always has absolute priority over the second key',
        'advancedkey.absolutePriority2Behavior': 'Absolute Priority Key2',
        'advancedkey.absolutePriority2BehaviorDesc': 'Second selected key always has absolute priority over the first key',
        'advancedkey.neutralBehavior': 'Neutral',
        'advancedkey.neutralBehaviorDesc': 'Both opposing inputs are canceled when pressed simultaneously',
        'advancedkey.distanceBehavior': 'Distance (Rappy Snappy)',
        'advancedkey.distanceBehaviorDesc': 'Priority based on key travel distance - deeper pressed key wins',
        'advancedkey.alternativeBottomOutBehavior': 'Alternative Bottom Out Behavior',
        'advancedkey.alternativeBottomOutBehaviorDesc': 'When both keys are bottomed out, register key press for both keys.',
        'advancedkey.bottomOutPointDesc': 'Set the distance at which the key is bottomed out.',
        'advancedkey.rapidTriggerDesc': 'Enable Rapid Trigger to resolve key events only when Rapid Trigger registers the key press. Adjust the sensitivity below.',
        'advancedkey.actuationPointDesc': 'Set the distance at which the key press is registered.',
        'advancedkey.keySensitivityWarning': 'the key may be too sensitive, causing instability, please be careful',
        'advancedkey.directInput': 'Direct input:',
        'advancedkey.rapidTriggerDownSensitivity': 'Rapid Trigger Down Sensitivity',
        'advancedkey.rapidTriggerDownSensitivityDesc': 'Set how sensitive the rapid trigger should be on key press.',
        'advancedkey.keyTesterTitle': 'Key Tester',
        'advancedkey.keyTesterDesc': 'Press the configured keys to test the null bind behavior',
        'advancedkey.key1': 'Key 1',
        'advancedkey.key2': 'Key 2',
        'advancedkey.priorityKey': 'Priority Key',
        'advancedkey.currentBehavior': 'Current Behavior:',
        'advancedkey.bottomOut': 'Bottom Out:',
        'advancedkey.configuredNullBindKeys': 'Configured Null Bind Keys',
        'advancedkey.pair': 'pair',
        'advancedkey.pairs': 'pairs',
        'advancedkey.pairedWith': 'Paired With:',        'advancedkey.behavior': 'Behavior:',
        'advancedkey.on': 'On',
        'advancedkey.off': 'Off',
        'advancedkey.resetAll': 'Reset All',
        
        // Toggle Page
        'advancedkey.toggleTitle': 'Toggle Configuration',
        'advancedkey.toggleSubtitle': 'Configure keys to toggle between two states',
        'advancedkey.toggleAction': 'Toggle Action',
        'advancedkey.toggleMode': 'Toggle Mode',
        'advancedkey.toggleState': 'Toggle State',
        'advancedkey.onPress': 'On Press',
        'advancedkey.onRelease': 'On Release',
        'advancedkey.enabled': 'Enabled',
        'advancedkey.disabled': 'Disabled',
        'advancedkey.system': 'System',
        'advancedkey.media': 'Media',
        'advancedkey.navigation': 'Navigation',
        'advancedkey.configuredToggle': 'Configured Toggle Keys',
        'advancedkey.toggleActionDesc': 'Action to toggle when activated',
        'advancedkey.toggleModeDesc': 'When the toggle should activate',
        'advancedkey.toggleStateDesc': 'Current state of the toggle',
        'advancedkey.howItWorks': 'How it works',
        'advancedkey.actions': 'Actions',
        'advancedkey.resetAllToggle': 'Reset All Toggle Keys',
        
        // Dynamic Page
        'advancedkey.dynamicTitle': 'Dynamic Keystroke Configuration',
        'advancedkey.dynamicSubtitle': 'Configure 4-phase keystroke control with analog input response',
        'advancedkey.bindings': 'Bindings',
        'advancedkey.performance': 'Performance',
        'advancedkey.keyTester': 'Key Tester',
        'advancedkey.bottomOutPoint': 'Bottom Out Point',
        'advancedkey.actuationPoint': 'Actuation Point',
        'advancedkey.rapidTrigger': 'Rapid Trigger',
        'advancedkey.continuousRapidTrigger': 'Continuous Rapid Trigger',
        'advancedkey.pressSensitivity': 'Press Sensitivity',
        'advancedkey.releaseSensitivity': 'Release Sensitivity',
        'advancedkey.configuredDynamic': 'Configured Dynamic Keys',
        'advancedkey.phaseControl': 'Phase Control',
        'advancedkey.analogResponse': 'Analog Response',
        'advancedkey.bindingIndex': 'Binding',
        'advancedkey.press': 'Press',
        'advancedkey.hold': 'Hold',
        'advancedkey.release': 'Release',
        'advancedkey.tap': 'Tap',
        'advancedkey.preview': 'Preview',        'advancedkey.testKeyDesc': 'Test your key configuration by pressing the selected key',        'advancedkey.resetAllDynamic': 'Reset All Dynamic Keys',
        'advancedkey.tipDynamic': 'Dynamic keys allow 4-phase control with analog input response for advanced customization',
        
        // Dynamic Keystroke Components
        'advancedkey.dynamicKeystroke': 'Dynamic Keystroke',
        'advancedkey.performanceSettings': 'Performance Settings',
        'advancedkey.testDynamicDesc': 'Test your dynamic keystroke configuration',
        'advancedkey.testKeyBehavior': 'Press the key to test dynamic keystroke behavior',
        'advancedkey.sensitivityWarning': 'the key may be too sensitive, causing instability, please be careful',        'advancedkey.keyPressedPastActuation': 'Key pressed past actuation point',
        'advancedkey.keyReleasedPastActuation': 'Key released past actuation point',
        'advancedkey.keyPressedPastBottomOut': 'Key pressed past bottom-out point',
        'advancedkey.keyReleasedPastBottomOut': 'Key released past bottom-out point',
        'advancedkey.rapidTriggerDisabled': 'Rapid Trigger Disabled',
        'advancedkey.rapidTriggerDisabledDesc': 'Rapid Trigger is automatically disabled when the key is bound to a DKS.',        'advancedkey.configureDKSBindings': 'Configure DKS Bindings',
        'advancedkey.dksBindingInstructions': 'Assign a keycode to each binding. Click nodes to create intervals, drag grips to resize, click bars to delete.',
        
        // Common Advanced Key Elements
        'advancedkey.configuration': 'Configuration',
        'advancedkey.settings': 'Settings',
        'advancedkey.timing': 'Timing',
        'advancedkey.sensitivity': 'Sensitivity',
        'advancedkey.millimeters': 'mm',
        'advancedkey.exportConfig': 'Export Configuration',        'advancedkey.importConfig': 'Import Configuration',
        
        // Advanced Key Common Elements  
        'advancedkey.keycodeSelection': 'Keycode Selection',
        'advancedkey.selectedKey': 'Selected Key',
        'advancedkey.position': 'Position',
        'advancedkey.noKeySelected': 'No Key Selected',
        'advancedkey.selectKeyToConfig': 'Select a key from the keyboard layout to configure its behavior',
        'advancedkey.tip': 'Tip',
        'advancedkey.keysCount': 'key',        'advancedkey.keysCountPlural': 'keys',        'advancedkey.resetAllTapHold': 'Reset All Tap Hold Keys',
        'advancedkey.tapHoldDescription': 'Perfect for modifier keys that can also function as regular keys when tapped quickly.',
        
        // Calibration Page
        'calibration.selectKeyStep': 'Select Key',
        'calibration.selectKeyDesc': 'Click on the key you want to calibrate',
        'calibration.startCalibrationStep': 'Start Calibration',
        'calibration.startCalibrationDesc': 'Begin the automatic calibration process',
        'calibration.testAdjustStep': 'Test & Adjust',
        'calibration.testAdjustDesc': 'Fine-tune the actuation points',
        'calibration.selected': 'Selected',
        'calibration.measuringRest': 'Measuring key at rest position...',
        'calibration.restComplete': 'Rest phase complete. Get ready...',
        
        // Layout/Common UI
        'ui.displayTooSmall': 'Display Too Small',
        'ui.displayTooSmallDesc': 'Zellia Control requires a larger display for the optimal keyboard configuration experience. Please use a desktop or laptop computer, or expand your browser window.',
        'ui.minimumWidth': 'Minimum recommended width: 1280px',
        'ui.featuresRequiringLarger': 'Features requiring larger display:',
        'ui.keyboardLayoutViz': 'Keyboard layout visualization',
        'ui.advancedKeyPanels': 'Advanced key configuration panels',
        'ui.performanceTuning': 'Performance tuning controls',
        'ui.lightingInterface': 'Lighting configuration interface',
        
        // Common Actions
        'common.apply': 'Apply',
        'common.save': 'Save',
        'common.cancel': 'Cancel',
        'common.reset': 'Reset',        'common.delete': 'Delete',
        'common.edit': 'Edit',
        'common.add': 'Add',
        'common.remove': 'Remove',
        'common.key': 'key',
        'common.keys': 'keys',
        'common.pair': 'pair',
        'common.pairs': 'pairs',
        'common.unknown': 'Unknown',        
        // Calibration - more keys
        'calibration.controls': 'Controls',
        'calibration.phase1': 'Phase 1: Measuring key at rest...',
        'calibration.phase2': 'Phase 2: Measuring key pressed...',
        'calibration.pressKeyNow': 'Press Key Now!',
        'calibration.deviceSettingsDesc': 'Device settings allow you to manage your keyboard\'s operational state. Choose actions carefully, especially factory reset which cannot be undone.',
        
        // Media Keys
        'media.mediaKeys': 'Media Keys',
        
        // Common Hardware
        'hardware.restMs': 'Rest: {0}mm',
        'hardware.pressedMs': 'Pressed: {0}mm',  
        'hardware.travelMs': 'Travel: {0}mm',
        'hardware.calibrationComplete': 'Calibration Complete!',
        
        // Advanced binding related
        'advancedkey.keycodeSelectionTitle': 'Keycode Selection',
        'advancedkey.selectKeycodeForBinding': 'Select a keycode for binding {0}',
        'advancedkey.clickOnBinding': 'Click on a binding button to select a keycode',
        'advancedkey.bindingsLabel': 'Bindings',
        'advancedkey.bottomOutLabel': 'Bottom Out',
        
        // Display messages
        'ui.noProfilesAvailable': 'No profiles available',
        'ui.featuresRequiringLargerDisplay': 'Features requiring larger display:',
        'ui.keyboardLayoutVisualization': 'Keyboard layout visualization',
        'ui.advancedKeyConfigPanels': 'Advanced key configuration panels',
        'ui.performanceTuningControls': 'Performance tuning controls',
        'ui.lightingConfigInterface': 'Lighting configuration interface',
        
        // Reset related
        'common.resetToDefault': 'Reset',
        'common.configure': 'Configure',
        'common.test': 'Test',
        
        // Debug Page
        'debug.title': 'Debug',
        'debug.keyPressReporting': 'Reports whether key is pressed',
        'debug.keyPressReportingDesc': 'Allows the keyboard to report whether a key is considered to be pressed. Pressed keys are indicated by the visual above.',
        'debug.reset': 'Reset',
        'debug.resetDesc': 'Reset the configuration of the device to default. Please wait for about half a minute before unplugging the device to ensure the configuration is saved.',
        'debug.resetButton': 'Reset',
        'debug.recoveryMode': 'Reboot to Recovery Mode',
        'debug.recoveryModeDesc': 'Reboot the device into recovery mode. Normally, you don\'t need to use this. If triggered by mistake, simply reconnect the device to recover.',
        'debug.recoveryModeButton': 'Reboot to Recovery Mode',
        'debug.keyTracking': 'Key Tracking',
        'debug.keyTrackingDesc': 'Track the pressing distance of a key in real time and visualize it in a chart for observation and analysis.',
        'debug.selectKey': 'Select Key',
        'debug.noKeySelected': 'No key selected',
        'debug.selectedKey': 'Selected',
        'debug.startTracking': 'Start Tracking (30s)',
        'debug.stopTracking': 'Stop Tracking',
        'debug.clearChart': 'Clear Chart',
        'debug.timeLabel': 'Time (ms)',
        'debug.distanceLabel': 'Distance (mm)',
        'debug.keyDistance': 'Key Distance',
          // Settings Page
        'settings.title': 'Settings',
        'settings.subtitle': 'Configure device settings and manage your keyboard',
        'settings.restart': 'Restart Device',
        'settings.restartDesc': 'Restart your keyboard to apply changes',
        'settings.restartFeature1': 'Applies pending configurations',
        'settings.restartFeature2': 'Refreshes device connection',
        'settings.restartFeature3': 'Quick restart process',
        'settings.restartFeature4': 'No data loss',
        'settings.bootloader': 'Enter Bootloader',
        'settings.bootloaderDesc': 'Enter bootloader mode for firmware updates',
        'settings.bootloaderFeature1': 'Firmware update mode',
        'settings.bootloaderFeature2': 'Advanced configuration access',
        'settings.bootloaderFeature3': 'Recovery capabilities',
        'settings.bootloaderFeature4': 'Expert users only',
        'settings.factoryReset': 'Factory Reset',
        'settings.factoryResetDesc': 'Reset all settings to factory defaults',
        'settings.factoryResetFeature1': 'Restores default settings',
        'settings.factoryResetFeature2': 'Clears all configurations',
        'settings.factoryResetFeature3': 'Cannot be undone',
        'settings.factoryResetFeature4': 'Fresh start guarantee',
          // About Page
        'about.title': 'About Zellia Control',
        'about.subtitle': 'Hall Effect keyboard configurator',
        'about.appName': 'Zellia Control',
        'about.appDescription': 'A powerful desktop application for configuring Zellia keyboards with Hall Effect switches. Built with modern web technologies for cross-platform compatibility and an intuitive user experience.',
        'about.version': 'Version 1.0.0',
        'about.builtWith': 'Built with Tauri & SvelteKit',
        'about.performance': 'Performance',
        'about.adjustableActuation': 'Adjustable actuation points (0-4mm)',
        'about.rapidTrigger': 'Rapid trigger technology',
        'about.realtimeMonitoring': 'Real-time pressure monitoring',
        'about.advancedKeys': 'Advanced Keys',
        'about.tapHold': 'Tap-hold functionality',
        'about.toggleModes': 'Toggle modes',
        'about.dynamicKeystroke': 'Dynamic keystroke control',
        'about.nullBind': 'Null bind with SOCD cleaning',
        'about.customization': 'Customization',
        'about.perKeyConfig': 'Per-key configuration',
        'about.profileManagement': 'Profile management',
        'about.lightingControl': 'Lighting control',
        'about.multiLayerSupport': 'Multi-layer support',
        'about.calibration': 'Calibration & Testing',
        'about.preciseCalibration': 'Precise switch calibration',
        'about.keyTracking': 'Real-time key tracking',
        'about.performanceTesting': 'Performance testing tools',
        'about.diagnostics': 'Hardware diagnostics',
        'about.madeWithLove': 'Made with love for the keyboard community',
        'about.rgbLighting': 'RGB lighting effects',
        'about.keyRemapping': 'Key remapping',
        'about.multipleThemes': 'Multiple theme colors',
        'about.darkLightMode': 'Dark/light mode support',
        'about.technical': 'Technical',
        'about.crossPlatform': 'Cross-platform support',
        'about.hardwareCalibration': 'Hardware calibration',
        'about.debugTools': 'Debug tools',
        'about.profileImportExport': 'Profile import/export',
          // Calibration Page
        'calibration.title': 'Calibration',
        'calibration.subtitle': 'Calibrate your keyboard switches for optimal performance',
        'calibration.start': 'Start Calibration',
        'calibration.reset': 'Reset Calibration',
        'calibration.instructions': 'Follow the on-screen instructions to calibrate your switches',
        
        // Lighting Page
        'lighting.title': 'Lighting',
        'lighting.subtitle': 'Customize RGB lighting effects and colors',
        'lighting.brightness': 'Brightness',
        'lighting.effects': 'Effects',
        'lighting.colors': 'Colors',
        'lighting.speed': 'Speed',
        'lighting.apply': 'Apply',
          // Remap Page
        'remap.title': 'Remap',
        'remap.subtitle': 'Remap keys to customize your keyboard layout',
        'remap.selectKey': 'Select a key to remap',
        'remap.currentMapping': 'Current Mapping',
        'remap.newMapping': 'New Mapping',
        'remap.save': 'Save',
        'remap.cancel': 'Cancel',
        'remap.reset': 'Reset to Default',
        'remap.basicKeys': 'Basic Keys',
        'remap.functionKeys': 'Function Keys',
        'remap.mediaKeys': 'Media Keys',
        'remap.mouse': 'Mouse',
        'remap.alphabet': 'Alphabet',
        'remap.numbers': 'Numbers',
        'remap.specialCharacters': 'Special Characters',
        'remap.mouseFunctions': 'Mouse Functions',
          // Units
        'units.mm': 'mm',
        'units.ms': 'ms',
    },
    zh: {
        // Navigation
        'nav.performance': '性能',
        'nav.remap': '按键映射',
        'nav.lighting': '灯光',
        'nav.advancedkey': '高级按键',
        'nav.calibration': '校准',
        'nav.debug': '调试',
        'nav.settings': '设置',
        'nav.about': '关于',
        
        // UI Elements
        'ui.sync': '同步',
        'ui.profiles': '配置文件',        'ui.import': '导入',
        'ui.export': '导出',
        'ui.back': '返回',
        'ui.themeColors': '主题颜色',
        'ui.lightMode': '浅色模式',
        'ui.darkMode': '深色模式',
        'ui.language': '语言',
        'ui.layer': '层级',
          // Common
        'common.zellia': 'Zellia 控制',
        'common.english': 'English',
        'common.chinese': '中文',
        'common.apply': '应用',
        'common.save': '保存',
        'common.cancel': '取消',
        'common.reset': '重置',
        'common.delete': '删除',
        'common.edit': '编辑',
        'common.add': '添加',
        'common.remove': '移除',
        'common.key': '按键',
        'common.keys': '按键',
        'common.pair': '对',
        'common.pairs': '对',
        'common.unknown': '未知',
        'common.resetToDefault': '重置',
        'common.configure': '配置',
        'common.test': '测试',
        
        // UI Elements - additional
        'ui.displayTooSmall': '显示过小',
        'ui.displayTooSmallDesc': 'Zellia 控制需要更大的显示器来获得最佳的键盘配置体验。请使用台式机或笔记本电脑，或扩展您的浏览器窗口。',
        'ui.minimumWidth': '最小推荐宽度：1280px',
        'ui.featuresRequiringLarger': '需要更大显示的功能：',
        'ui.keyboardLayoutViz': '键盘布局可视化',
        'ui.advancedKeyPanels': '高级按键配置面板',
        'ui.performanceTuning': '性能调优控制',
        'ui.lightingInterface': '灯光配置界面',
        'ui.noProfilesAvailable': '无可用配置文件',
        'ui.featuresRequiringLargerDisplay': '需要更大显示的功能：',
        'ui.keyboardLayoutVisualization': '键盘布局可视化',
        'ui.advancedKeyConfigPanels': '高级按键配置面板',
        'ui.performanceTuningControls': '性能调优控制',
        'ui.lightingConfigInterface': '灯光配置界面',
        
        // Media Keys
        'media.mediaKeys': '媒体键',
        
        // Hardware
        'hardware.restMs': '静止：{0}mm',
        'hardware.pressedMs': '按下：{0}mm',
        'hardware.travelMs': '行程：{0}mm',
        'hardware.calibrationComplete': '校准完成！',
        
        // Performance Page
        'performance.title': '性能',
        'performance.selectAllKeys': '选择所有按键',
        'performance.discardSelection': '取消选择',
        'performance.actuationPoint': '触发点',
        'performance.actuationPointDesc': '设置按键的触发点。',
        'performance.actuationPointLabel': '触发点',
        'performance.sensitivityWarning': '按键可能过于敏感，可能导致不稳定，请小心',
        'performance.rapidTrigger': '快速触发',
        'performance.rapidTriggerDesc': '启用快速触发以获得更快的按键响应。',
        'performance.continuousRapidTrigger': '连续快速触发',
        'performance.continuousRapidTriggerDesc': '持续维持快速触发状态。',
        'performance.sensitivity': '灵敏度',
        'performance.separateSensitivity': '分离按下/释放灵敏度',
        'performance.pressSensitivity': '按下灵敏度',
        'performance.releaseSensitivity': '释放灵敏度',
        'performance.enableRapidTrigger': '启用快速触发',
        'performance.enableContinuousRapidTrigger': '启用连续快速触发',
        'performance.continuousRapidTriggerFullDesc': '启用时，快速触发在整个按键释放时结束。禁用时，快速触发在触发点结束。',
        'performance.rapidTriggerSensitivity': '快速触发灵敏度',
        'performance.adjustSensitivity': '调整快速触发的灵敏度。',
        'performance.pressSensitivityLabel': '按下灵敏度',
        'performance.releaseSensitivityLabel': '释放灵敏度',
        'performance.sensitivityLabel': '灵敏度',
        'performance.keysSelected': '个按键已选择',
        'performance.high': '高',
        'performance.low': '低',
        'performance.directInput': '直接输入',
        
        // Debug Page
        'debug.title': '调试',
        'debug.keyPressReporting': '报告按键是否被按下',
        'debug.keyPressReportingDesc': '允许键盘报告按键是否被认为被按下。被按下的按键在上方的视觉显示中指示。',
        'debug.reset': '重置',
        'debug.resetDesc': '将设备配置重置为默认值。请等待约半分钟后再拔掉设备，以确保配置被保存。',
        'debug.resetButton': '重置',
        'debug.recoveryMode': '重启到恢复模式',
        'debug.recoveryModeDesc': '将设备重启到恢复模式。通常情况下，您不需要使用此功能。如果误触发，只需重新连接设备即可恢复。',
        'debug.recoveryModeButton': '重启到恢复模式',
        'debug.keyTracking': '按键跟踪',
        'debug.keyTrackingDesc': '实时跟踪按键的按下距离，并在图表中可视化以供观察和分析。',
        'debug.selectKey': '选择按键',
        'debug.noKeySelected': '未选择按键',
        'debug.selectedKey': '已选择',
        'debug.startTracking': '开始跟踪 (30秒)',
        'debug.stopTracking': '停止跟踪',
        'debug.clearChart': '清除图表',
        'debug.timeLabel': '时间 (毫秒)',
        'debug.distanceLabel': '距离 (毫米)',
        'debug.keyDistance': '按键距离',
          // Settings Page
        'settings.title': '设置',
        'settings.subtitle': '配置设备设置并管理您的键盘',
        'settings.restart': '重启设备',
        'settings.restartDesc': '重启键盘以应用更改',
        'settings.restartFeature1': '应用待处理的配置',
        'settings.restartFeature2': '刷新设备连接',
        'settings.restartFeature3': '快速重启过程',
        'settings.restartFeature4': '无数据丢失',
        'settings.bootloader': '进入引导程序',
        'settings.bootloaderDesc': '进入引导程序模式进行固件更新',
        'settings.bootloaderFeature1': '固件更新模式',
        'settings.bootloaderFeature2': '高级配置访问',
        'settings.bootloaderFeature3': '恢复功能',
        'settings.bootloaderFeature4': '仅限专家用户',
        'settings.factoryReset': '恢复出厂设置',
        'settings.factoryResetDesc': '将所有设置重置为出厂默认值',
        'settings.factoryResetFeature1': '恢复默认设置',
        'settings.factoryResetFeature2': '清除所有配置',
        'settings.factoryResetFeature3': '无法撤销',
        'settings.factoryResetFeature4': '保证全新开始',
          // About Page
        'about.title': '关于 Zellia 控制',
        'about.subtitle': '霍尔效应键盘配置器',
        'about.appName': 'Zellia 控制',
        'about.appDescription': '一个强大的桌面应用程序，用于配置带有霍尔效应开关的 Zellia 键盘。采用现代网络技术构建，具有跨平台兼容性和直观的用户体验。',
        'about.version': '版本 1.0.0',
        'about.builtWith': '使用 Tauri 和 SvelteKit 构建',
        'about.performance': '性能',
        'about.adjustableActuation': '可调节触发点 (0-4毫米)',
        'about.rapidTrigger': '快速触发技术',
        'about.realtimeMonitoring': '实时压力监控',
        'about.advancedKeys': '高级按键',
        'about.tapHold': '轻按保持功能',
        'about.toggleModes': '切换模式',
        'about.dynamicKeystroke': '动态按键控制',
        'about.nullBind': '空绑定与SOCD清理',
        'about.customization': '自定义',
        'about.perKeyConfig': '按键级配置',
        'about.profileManagement': '配置文件管理',
        'about.lightingControl': '灯光控制',
        'about.multiLayerSupport': '多层支持',
        'about.calibration': '校准与测试',
        'about.preciseCalibration': '精确开关校准',
        'about.keyTracking': '实时按键跟踪',
        'about.performanceTesting': '性能测试工具',
        'about.diagnostics': '硬件诊断',
        'about.madeWithLove': '为键盘社区倾情打造',
        'about.rgbLighting': 'RGB灯光效果',
        'about.keyRemapping': '按键重映射',
        'about.multipleThemes': '多种主题颜色',
        'about.darkLightMode': '深色/浅色模式支持',
        'about.technical': '技术',
        'about.crossPlatform': '跨平台支持',        'about.hardwareCalibration': '硬件校准',
        'about.debugTools': '调试工具',
        'about.profileImportExport': '配置文件导入/导出',
          // Calibration Page
        'calibration.title': '校准',
        'calibration.subtitle': '校准您的键盘开关以获得最佳性能',
        'calibration.start': '开始校准',
        'calibration.reset': '重置校准',
        'calibration.instructions': '按照屏幕指示校准您的开关',
        'calibration.selectKeyStep': '选择按键',
        'calibration.selectKeyDesc': '点击您想要校准的按键',
        'calibration.startCalibrationStep': '开始校准',
        'calibration.startCalibrationDesc': '开始自动校准过程',
        'calibration.testAdjustStep': '测试与调整',
        'calibration.testAdjustDesc': '微调触发点',
        'calibration.selected': '已选择',
        'calibration.measuringRest': '测量按键静止位置...',
        'calibration.restComplete': '静止阶段完成。准备好...',
        'calibration.controls': '控制',
        'calibration.phase1': '阶段1：测量按键静止状态...',
        'calibration.phase2': '阶段2：测量按键按下状态...',
        'calibration.pressKeyNow': '现在按下按键！',
        'calibration.deviceSettingsDesc': '设备设置允许您管理键盘的运行状态。请谨慎选择操作，特别是恢复出厂设置无法撤销。',// Lighting Page
        'lighting.title': '灯光',
        'lighting.subtitle': '自定义RGB灯光效果和颜色',
        'lighting.brightness': '亮度',
        'lighting.effects': '效果',
        'lighting.color': '颜色',
        'lighting.colors': '颜色',
        'lighting.speed': '速度',
        'lighting.apply': '应用',
        'lighting.static': '静态',
        'lighting.staticDesc': '单一纯色',
        'lighting.breathing': '呼吸',
        'lighting.breathingDesc': '平滑淡入淡出',
        'lighting.wave': '波浪',
        'lighting.waveDesc': '整个键盘的颜色波浪',
        'lighting.ripple': '涟漪',
        'lighting.rippleDesc': '按键时的涟漪效果',
        'lighting.rainbow': '彩虹',
        'lighting.rainbowDesc': '循环彩虹颜色',
        'lighting.reactive': '反应',
        'lighting.reactiveDesc': '按键时颜色变化',
        'lighting.spectrum': '光谱',
        'lighting.spectrumDesc': '颜色光谱循环',
        'lighting.gradient': '渐变',
        'lighting.gradientDesc': '自定义颜色渐变',
        'lighting.direction': '方向',
        'lighting.leftToRight': '从左到右',
        'lighting.rightToLeft': '从右到左',
        'lighting.topToBottom': '从上到下',
        'lighting.bottomToTop': '从下到上',
        'lighting.centerOut': '中心向外',
        'lighting.outsideIn': '外围向内',
        
        // Lighting UI
        'lighting.applySettings': '应用设置',
        'lighting.perKeyMode': '按键模式',
        'lighting.exitPerKeyMode': '退出按键模式',
        'lighting.colorSettings': '颜色设置',
        'lighting.perKeyModeActive': '按键模式激活',
        'lighting.clickKeysToSelect': '点击键盘上的按键来选择它们',
        'lighting.keyColor': '按键颜色',
        'lighting.selectKey': '选择按键',
        'lighting.deselectKey': '取消选择按键',
        'lighting.clear': '清除',
        'lighting.applyToSelectedKeys': '应用到选中的按键',
        'lighting.gradientColors': '渐变颜色',
        'lighting.addColor': '添加颜色',
        'lighting.preview': '预览',
        'lighting.automaticColors': '此效果使用自动颜色',
        'lighting.noColorSettings': '此效果不需要颜色设置',        'lighting.animatedEffect': '动画效果',
        'lighting.reactiveEffect': '反应效果',
        'lighting.rgbValues': 'RGB: {0}, {1}, {2}',
          // Remap Page
        'remap.title': '按键映射',
        'remap.subtitle': '重新映射按键以自定义键盘布局',
        'remap.selectKey': '选择要重新映射的按键',
        'remap.currentMapping': '当前映射',
        'remap.newMapping': '新映射',
        'remap.save': '保存',
        'remap.cancel': '取消',
        'remap.reset': '重置为默认',          // Advanced Key Page
        'advancedkey.title': '高级按键',
        'advancedkey.subtitle': '配置高级键盘行为以提高生产力',
        'advancedkey.gettingStarted': '入门指南',
        'advancedkey.step1Title': '选择模式',
        'advancedkey.step1Desc': '选择要配置的高级按键行为',
        'advancedkey.step2Title': '选择按键',
        'advancedkey.step2Desc': '在键盘布局中点击按键来配置它们',
        'advancedkey.step3Title': '应用设置',
        'advancedkey.step3Desc': '将配置保存到键盘',
        'advancedkey.infoDesc': '高级按键配置允许您自定义单个按键的行为，超越标准打字。每种模式都提供独特的功能来增强您的键盘体验。',
        
        // Advanced Key Modes
        'advancedkey.tapHold': '轻按保持',
        'advancedkey.tapHoldDesc': '轻按与保持的不同操作',
        'advancedkey.tapHoldFeature1': '快速轻按操作',
        'advancedkey.tapHoldFeature2': '可配置延迟的保持操作',
        'advancedkey.tapHoldFeature3': '完美适用于修饰键',
        'advancedkey.tapHoldFeature4': '可自定义时间',        'advancedkey.tapHoldTip': '轻按保持按键非常适合既可作为修饰键又可在快速轻按时作为常规按键的功能',        'advancedkey.quickTap': '快速轻按（少于 {0} 毫秒）',
        'advancedkey.holdOver': '按住（超过 {0} 毫秒）',
        
        'advancedkey.toggle': '切换',
        'advancedkey.toggleDesc': '在两个状态之间切换',
        'advancedkey.toggleFeature1': '按下或释放时切换',
        'advancedkey.toggleFeature2': '完美适用于大写锁定行为',
        'advancedkey.toggleFeature3': '状态持久化',        'advancedkey.toggleFeature4': '视觉反馈',
        'advancedkey.toggleDescription': '此按键将在{1}切换{0}。每次触发都会在激活和非激活状态之间切换。',
        'advancedkey.whenPressed': '按下时',
        'advancedkey.whenReleased': '释放时',
        
        'advancedkey.dynamic': '动态按键',
        'advancedkey.dynamicDesc': '交互式按键配置',
        'advancedkey.dynamicFeature1': '4相按键控制',
        'advancedkey.dynamicFeature2': '模拟输入响应',
        'advancedkey.dynamicFeature3': '多按键绑定',
        'advancedkey.dynamicFeature4': '高级自定义',
        
        'advancedkey.nullBind': '空绑定',
        'advancedkey.nullBindDesc': '快速触发与SOCD清理',
        'advancedkey.nullBindFeature1': '快速触发技术',
        'advancedkey.nullBindFeature2': 'SOCD（同时相对基本方向）',
        'advancedkey.nullBindFeature3': '完美适用于游戏',
        'advancedkey.nullBindFeature4': '超响应输入',
        
        // Tap-Hold Page
        'advancedkey.tapHoldTitle': '轻按保持配置',
        'advancedkey.tapHoldSubtitle': '为快速轻按与长按保持配置不同的操作',
        'advancedkey.tapAction': '轻按操作',
        'advancedkey.holdAction': '保持操作',
        'advancedkey.holdDelay': '保持延迟',
        'advancedkey.tapTimeout': '轻按超时',
        'advancedkey.milliseconds': '毫秒',
        'advancedkey.tapActionDesc': '快速轻按时执行的操作',
        'advancedkey.holdActionDesc': '保持时执行的操作',
        'advancedkey.holdDelayDesc': '保持操作激活前的时间',
        'advancedkey.tapTimeoutDesc': '轻按检测的最大时间',
        'advancedkey.configuredTapHold': '已配置的轻按保持按键',
        'advancedkey.actionCategories': '操作类别',
        'advancedkey.common': '常用',
        'advancedkey.modifiers': '修饰键',
        'advancedkey.function': '功能键',
        'advancedkey.letters': '字母',
        'advancedkey.backToAdvanced': '返回',
        'advancedkey.applyConfiguration': '应用配置',
        'advancedkey.resetConfiguration': '重置配置',
        
        // Null Bind Page
        'advancedkey.nullBindTitle': '空绑定配置',
        'advancedkey.nullBindSubtitle': '为游戏配置快速触发与SOCD清理',
        'advancedkey.socdBehavior': 'SOCD行为',
        'advancedkey.lastInput': '最后输入',
        'advancedkey.lastInputDesc': '最近按下的按键获得优先权',
        'advancedkey.absolutePriority1': '按键1绝对优先',
        'advancedkey.absolutePriority1Desc': '第一个选择的按键总是有优先权',
        'advancedkey.absolutePriority2': '按键2绝对优先',
        'advancedkey.absolutePriority2Desc': '第二个选择的按键总是有优先权',
        'advancedkey.neutral': '中性',
        'advancedkey.neutralDesc': '冲突时两个按键都释放',        'advancedkey.distance': '距离',
        'advancedkey.distanceDesc': '行程距离更大的按键获胜',
        
        // Null Bind Page - Additional translations
        'advancedkey.selectTwoKeys': '选择两个按键',
        'advancedkey.selectTwoKeysDesc': '在键盘布局中点击两个相对的按键来配置空绑定行为。按键将自动添加。',
        'advancedkey.firstKey': '第一个按键',
        'advancedkey.secondKey': '第二个按键',
        'advancedkey.clickKeyToSelect': '点击按键选择',
        'advancedkey.clickOpposingKey': '点击相对按键',
        'advancedkey.remove': '移除',
        'advancedkey.resetSelection': '重置选择',
        'advancedkey.selectedKeys': '选中的按键',
        'advancedkey.configureNullBindBehavior': '配置空绑定行为',
        'advancedkey.selectHowToResolveKeyEvents': '选择如何解决同时按下两个按键时的按键事件。',
        'advancedkey.lastInputBehavior': '最后输入',
        'advancedkey.lastInputBehaviorDesc': '最近按下的按键优先于之前保持的按键',
        'advancedkey.absolutePriority1Behavior': '按键1绝对优先',
        'advancedkey.absolutePriority1BehaviorDesc': '第一个选择的按键总是绝对优先于第二个按键',
        'advancedkey.absolutePriority2Behavior': '按键2绝对优先',
        'advancedkey.absolutePriority2BehaviorDesc': '第二个选择的按键总是绝对优先于第一个按键',
        'advancedkey.neutralBehavior': '中性',
        'advancedkey.neutralBehaviorDesc': '同时按下时两个相对输入都被取消',
        'advancedkey.distanceBehavior': '距离 (Rappy Snappy)',
        'advancedkey.distanceBehaviorDesc': '基于按键行程距离的优先级 - 按得更深的按键获胜',
        'advancedkey.alternativeBottomOutBehavior': '替代到底行为',
        'advancedkey.alternativeBottomOutBehaviorDesc': '当两个按键都到底时，为两个按键都注册按键事件。',
        'advancedkey.bottomOutPointDesc': '设置按键到底的距离。',
        'advancedkey.rapidTriggerDesc': '启用快速触发以仅在快速触发注册按键事件时解决按键事件。在下方调整灵敏度。',
        'advancedkey.actuationPointDesc': '设置注册按键事件的距离。',
        'advancedkey.keySensitivityWarning': '按键可能过于敏感，导致不稳定，请小心',
        'advancedkey.directInput': '直接输入：',
        'advancedkey.rapidTriggerDownSensitivity': '快速触发下压灵敏度',
        'advancedkey.rapidTriggerDownSensitivityDesc': '设置按键时快速触发的灵敏度。',
        'advancedkey.keyTesterTitle': '按键测试器',
        'advancedkey.keyTesterDesc': '按下配置的按键来测试空绑定行为',
        'advancedkey.key1': '按键1',
        'advancedkey.key2': '按键2',
        'advancedkey.priorityKey': '优先按键',
        'advancedkey.currentBehavior': '当前行为：',
        'advancedkey.bottomOut': '到底：',
        'advancedkey.configuredNullBindKeys': '已配置的空绑定按键',
        'advancedkey.pair': '对',
        'advancedkey.pairs': '对',
        'advancedkey.pairedWith': '配对：',        'advancedkey.behavior': '行为：',
        'advancedkey.on': '开',
        'advancedkey.off': '关',
        'advancedkey.resetAll': '重置全部',
        
        // Toggle Page
        'advancedkey.toggleTitle': '切换配置',
        'advancedkey.toggleSubtitle': '配置按键在两个状态之间切换',
        'advancedkey.toggleAction': '切换操作',
        'advancedkey.toggleMode': '切换模式',
        'advancedkey.toggleState': '切换状态',
        'advancedkey.onPress': '按下时',
        'advancedkey.onRelease': '释放时',
        'advancedkey.enabled': '启用',
        'advancedkey.disabled': '禁用',
        'advancedkey.system': '系统',
        'advancedkey.media': '媒体',
        'advancedkey.navigation': '导航',
        'advancedkey.configuredToggle': '已配置的切换按键',
        'advancedkey.toggleActionDesc': '激活时要切换的操作',
        'advancedkey.toggleModeDesc': '切换应何时激活',
        'advancedkey.toggleStateDesc': '切换的当前状态',
        'advancedkey.howItWorks': '工作原理',
        'advancedkey.actions': '操作',
        'advancedkey.resetAllToggle': '重置所有切换按键',
        
        // Dynamic Page
        'advancedkey.dynamicTitle': '动态按键配置',
        'advancedkey.dynamicSubtitle': '配置4相按键控制与模拟输入响应',
        'advancedkey.bindings': '绑定',
        'advancedkey.performance': '性能',
        'advancedkey.keyTester': '按键测试器',
        'advancedkey.bottomOutPoint': '到底点',
        'advancedkey.actuationPoint': '触发点',
        'advancedkey.rapidTrigger': '快速触发',
        'advancedkey.continuousRapidTrigger': '连续快速触发',
        'advancedkey.pressSensitivity': '按下灵敏度',
        'advancedkey.releaseSensitivity': '释放灵敏度',
        'advancedkey.configuredDynamic': '已配置的动态按键',
        'advancedkey.phaseControl': '相位控制',
        'advancedkey.analogResponse': '模拟响应',
        'advancedkey.bindingIndex': '绑定',
        'advancedkey.press': '按下',
        'advancedkey.hold': '保持',
        'advancedkey.release': '释放',
        'advancedkey.tap': '轻按',
        'advancedkey.preview': '预览',
        'advancedkey.testKeyDesc': '通过按下选中的按键测试您的按键配置',        'advancedkey.resetAllDynamic': '重置所有动态按键',
        
        // Dynamic Keystroke Components
        'advancedkey.dynamicKeystroke': '动态按键',
        'advancedkey.performanceSettings': '性能设置',
        'advancedkey.testDynamicDesc': '测试您的动态按键配置',
        'advancedkey.testKeyBehavior': '按下按键测试动态按键行为',
        'advancedkey.sensitivityWarning': '按键可能过于敏感，导致不稳定，请小心使用',        'advancedkey.keyPressedPastActuation': '按键按下超过触发点',
        'advancedkey.keyReleasedPastActuation': '按键释放超过触发点',
        'advancedkey.keyPressedPastBottomOut': '按键按下超过底部撞击点',
        'advancedkey.keyReleasedPastBottomOut': '按键释放超过底部撞击点',        'advancedkey.rapidTriggerDisabled': '快速触发已禁用',
        'advancedkey.rapidTriggerDisabledDesc': '当按键绑定到DKS时，快速触发会自动禁用。',
        'advancedkey.configureDKSBindings': '配置DKS绑定',
        'advancedkey.dksBindingInstructions': '为每个绑定分配按键代码。点击节点创建间隔，拖动手柄调整大小，点击条形图删除。',
        
        // Common Advanced Key Elements
        'advancedkey.mode': '模式',
        'advancedkey.configuration': '配置',
        'advancedkey.settings': '设置',
        'advancedkey.timing': '时间',
        'advancedkey.sensitivity': '灵敏度',
        'advancedkey.millimeters': '毫米',
        'advancedkey.exportConfig': '导出配置',
        'advancedkey.importConfig': '导入配置',
        'advancedkey.keycodeSelectionTitle': '按键代码选择',
        
        // Advanced Key Common Elements  
        'advancedkey.keycodeSelection': '按键代码选择',
        'advancedkey.selectedKey': '选中的按键',
        'advancedkey.position': '位置',
        'advancedkey.noKeySelected': '未选择按键',
        'advancedkey.selectKeyToConfig': '从键盘布局中选择一个按键来配置其行为',
        'advancedkey.tip': '提示',
        'advancedkey.keysCount': '个按键',        'advancedkey.keysCountPlural': '个按键',        'advancedkey.resetAllTapHold': '重置所有轻按保持按键',
        'advancedkey.tapHoldDescription': '非常适合既可作为修饰键又可在快速轻按时作为常规按键的功能。',
        'advancedkey.tipDynamic': '动态按键允许4相控制与模拟输入响应进行高级自定义',
        
        // Advanced binding related
        'advancedkey.selectKeycodeForBinding': '为绑定 {0} 选择按键代码',
        'advancedkey.clickOnBinding': '点击绑定按钮选择按键代码',
        'advancedkey.bindingsLabel': '绑定',
        'advancedkey.bottomOutLabel': '触底',
        'units.mm': 'mm',
        'units.ms': 'ms',
    }
};

// Translation function
export const t = (key: string, lang: Language): string => {
    return translations[lang][key as keyof typeof translations.en] || key;
};

// Translation function with placeholder support
export const tPlaceholder = (key: string, lang: Language, ...args: string[]): string => {
    let text = translations[lang][key as keyof typeof translations.en] || key;
    args.forEach((arg, index) => {
        text = text.replace(`{${index}}`, arg);
    });
    return text;
};
