import { registerSW } from 'virtual:pwa-register';

export interface RegisterServiceWorkerOptions {
  /**
   * Called instead of the default page reload when an updated service worker has taken control
   * (autoUpdate), e.g. to postpone the reload while a keyboard session is active.
   */
  onNeedReload?: () => void;
}

let registered = false;

/**
 * Registers the Workbox service worker generated by vite-plugin-pwa (`registerType: 'autoUpdate'`):
 * offline precache of the app shell, and a new deployment activates immediately and reloads the
 * page. workbox-window defers registration to the window `load` event. Idempotent; a no-op in dev,
 * where vite-plugin-pwa serves a stub module.
 */
export function registerServiceWorker(options: RegisterServiceWorkerOptions = {}): void {
  if (registered) return;
  registered = true;
  registerSW({
    ...(options.onNeedReload ? { onNeedReload: options.onNeedReload } : {}),
    onRegisterError(error: unknown) {
      console.error('Service worker registration failed', error);
    },
  });
}
