import { registerSW } from 'virtual:pwa-register';

/** Decides when a downloaded app update may take over the page. */
export interface UpdatePolicy {
  /** True when reloading the page cannot interrupt anything (no keyboard session, no flash). */
  isIdle(): boolean;
  /** Notifies whenever `isIdle()` may have changed; returns an unsubscribe function. */
  subscribe(listener: () => void): () => void;
}

let registered = false;

/**
 * Registers the Workbox service worker generated by vite-plugin-pwa (`registerType: 'prompt'`):
 * offline precache of the app shell. A new deployment installs as a *waiting* worker, so the
 * current page keeps running on the old worker and its precache (its lazy route chunks stay
 * loadable even after the deploy removed them from the server). The update is applied — the
 * waiting worker is activated and the page reloads — only while `policy.isIdle()`, so it can
 * never interrupt a connected keyboard or a firmware flash. There is no update prompt UI.
 *
 * Idempotent; a no-op in dev, where vite-plugin-pwa serves a stub module.
 */
export function registerServiceWorker(policy: UpdatePolicy): void {
  if (registered) return;
  registered = true;

  let updatePending = false;
  let unsubscribe: (() => void) | null = null;

  const applyWhenIdle = () => {
    if (!updatePending) return;
    if (!policy.isIdle()) {
      unsubscribe ??= policy.subscribe(applyWhenIdle);
      return;
    }
    updatePending = false;
    unsubscribe?.();
    unsubscribe = null;
    void updateServiceWorker(true);
  };

  const updateServiceWorker = registerSW({
    onNeedRefresh() {
      updatePending = true;
      applyWhenIdle();
    },
    onRegisterError(error: unknown) {
      console.error('Service worker registration failed', error);
    },
  });
}
