import { writable } from 'svelte/store';
import * as ekc from 'emi-keyboard-controller';

export const advancedKeys = writable(Array<ekc.IAdvancedKey>());
export const rgbConfigs = writable(Array<ekc.IRGBConfig>());
export const keymap = writable(Array<Array<number>>());
export const rgbBaseConfig = writable(new ekc.RGBBaseConfig());
export const dynamicKeys = writable(Array<ekc.IDynamicKey>());
export const layoutLabels = writable<string[][]>([[]]);
export const selectedLayoutIndices = writable<number[]>([]);
export const keyboardConfig = writable(new ekc.KeyboardConfig());
export const firmwareVersion = writable<ekc.FirmwareVersion>({ major: 0, minor: 0, patch: 0, info: '' });
export const firmwareFeature = writable(new ekc.Feature());
export const profileIndex = writable(0);
export const profileCount = writable(0);
export const macros = writable<ekc.IMacroAction[][]>([[]]);
export const scriptSource = writable('');
export const scriptBytecode = writable(new Uint8Array());
export const configHydrationStatus = writable<'idle' | 'loading' | 'ready' | 'error'>('idle');
export const configHydrationError = writable<string | null>(null);
