name: Build and Deploy Website

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
  pull_request:
    branches:
      - main
    paths:
      - 'src/**'
  workflow_dispatch: # Manual trigger

env:
  NODE_VERSION: '20'
  YARN_VERSION: '1.22.22'

jobs:
  build:
    name: Build Website
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'yarn'

      - name: Setup Yarn
        run: |
          corepack enable
          yarn set version ${{ env.YARN_VERSION }}

      - name: Install dependencies
        run: yarn install

      - name: Build website
        run: yarn build
        env:
          NODE_ENV: production

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: website-build
          path: build/
          compression-level: 9

  deploy:
    environment: "configurator.zellia.cn"
    name: Deploy Website
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
    
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: website-build
          path: build/

      - name: Deploy to server
        uses: Burnett01/rsync-deployments@7.0.2
        with:
          switches: '-avz --delete'
          path: 'build/'
          remote_path: ${{ secrets.DEPLOY_PATH }}
          remote_host: ${{ secrets.DEPLOY_HOST }}
          remote_user: ${{ secrets.DEPLOY_USER }}
          remote_port: ${{ secrets.DEPLOY_PORT }} 
          remote_key: ${{ secrets.DEPLOY_SSH_KEY }}
